# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["usb_storage" "usbhid" "vc4"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    fsType = "tmpfs";
    options = ["mode=0755" "size=20%"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "ext4";
  };

  fileSystems."/boot/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    device = "/dev/nixos-sd/nix";
    fsType = "f2fs";
    options = ["compress_algorithm=zstd" "compress_chksum" "atgc" "gc_merge" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/nixos-sd/persist";
    fsType = "f2fs";
    options = ["compress_algorithm=zstd" "compress_chksum" "atgc" "gc_merge" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/var" = {
    device = "/dev/nixos-sd/var";
    fsType = "f2fs";
    options = ["compress_algorithm=zstd" "compress_chksum" "atgc" "gc_merge" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/home/chris" = {
    device = "/dev/nixos-sd/home";
    fsType = "f2fs";
    options = ["compress_algorithm=zstd" "compress_chksum" "atgc" "gc_merge" "noatime"];
  };

  fileSystems."/media/storage" = {
    device = "/dev/disk/by-label/STORAGE";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "nofail"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
