# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@" "compression=zstd" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@nix" "compression=zstd" "noatime"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@tmp" "compression=zstd:1" "noatime"];
  };

  fileSystems."/home/chris" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@home-chris" "compression=zstd" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@persist" "compression=zstd" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@var-cache" "compression=zstd" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/var/lib" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@var-lib" "compression=zstd" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@var-log" "compression=zstd" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@var-tmp" "compression=zstd:1" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-label/rootfs";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2178-694E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/swap/swapfile";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
